name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: |
        poetry install
    - name: Run checks and lint code
      run: |
        poetry run ./tasks.py lint
    - name: Run tests
      run: |
        poetry run ./tasks.py test
